<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/8/21
 * Time: 22:18
 */
namespace app\models;

use yii\db\ActiveRecord;

class Test extends ActiveRecord
{

    public static function tableName()
    {
        return "{{test}}"; // TODO: Change the autogenerated stub
    }
}
